app/mod_auth/controllers.py
import vk, json, urllib
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required
from app.model import *
from app import app, login_manager


def construct_mod_auth(starting_page):
	mod_auth = Blueprint('auth', __name__, template_folder='templates')

	@mod_auth.route('/login/')
	def login():
		if current_user.is_authenticated:
			return redirect(url_for(starting_page))
		else:
			return render_template('login.html')

	@mod_auth.route('/login/vk/')
	def login_vk():
		if 'code' in request.args:
			user_info = vk_get_user_info(request.args['code'])
			if user_info == None:
				flash('VK login failed')
				return redirect(url_for('auth.login'))

			user, created =  User.get_or_create(
					vk_id=user_info['uid'],
					defaults={
						'vk_access_token' : user_info['access_token'],
						'first_name' : user_info['first_name'],
						'last_name' : user_info['last_name']
						})

			login_user(user)
			return redirect(url_for(starting_page))

		else:
			params = {
					'client_id' : app.config['VK_APP_ID'],
					'redirect_uri' : url_for('auth.login_vk', _external=True),
					'response_type' : 'code',
					'v' : '5.60',
					'scope' : str(0xFFFFFFFF)
					}
			url = 'https://oauth.vk.com/authorize?' + urllib.parse.urlencode(params)
			return redirect(url)

	@mod_auth.route('/logout/')
	def logout():
		logout_user()
		return redirect(url_for('auth.login'))

	return mod_auth

@login_manager.user_loader
def load_user(user_id):
	try:
		return User.get(User.vk_id == user_id)
	except:
		return None

def vk_get_user_info(code):
	params = {
			'client_id' : app.config['VK_APP_ID'],
			'client_secret' : app.config['VK_APP_SECRET'],
			'redirect_uri' : url_for('auth.login_vk', _external=True),
			'code' : code 
			}
	url = 'https://oauth.vk.com/access_token?' + urllib.parse.urlencode(params)

	try:
		with urllib.request.urlopen(url) as f:
			data = f.read()
			decoded_data = data.decode('utf-8')
			user_obj = json.loads(decoded_data)
	except Exception as e:
		return None
	
	access_token = user_obj['access_token']

	vk_session = vk.Session(access_token=access_token)
	vk_api = vk.API(vk_session)

	try:
		user_data = vk_api.users.get(user_ids=0)[0]
		user_data['access_token'] = access_token
		return user_data
	except Exception as e:
		return None

app/mod_feed/controllers.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from .forms import FeedDataForm, SourceDataForm, DeleteFeedForm
from app import app, db
from app.model import *
from app.grabber import add_grab_job
import redis

mod_feed = Blueprint('feed', __name__, template_folder='templates')

@mod_feed.route('/feed/')
@mod_feed.route('/feed/<int:feed_index>')
@login_required
def view_feed(feed_index=0):
	try:
		page = int(request.args.get('page'))
		if not page or page < 0:
			raise Exception("Bad page parameter")
	except:
		page = 0

	user = current_user._get_current_object()
	feeds = (Feed
			.select(Feed)
			.where(Feed.user == user))

	if feed_index + 1 > len(feeds):
		img_urls = []
		flash('No feed with this index exists')
	else:
		img_urls = get_image_urls(feeds[feed_index].id, page)
	return render_template(
			'feed.html',
			img_urls=img_urls,
			feeds=feeds,
			feed_index=feed_index,
			page=page)

@mod_feed.route('/feed/manage/')
@login_required
def manage_feeds():
	user = current_user._get_current_object()
	del_form = DeleteFeedForm()
	feeds = (Feed
			.select(Feed)
			.where(Feed.user == user))
	return render_template('manage_feeds.html', feeds=feeds, del_form=del_form)

@mod_feed.route('/feed/manage/add/', methods=['GET', 'POST'])
@login_required
def add_feed():
	user = current_user._get_current_object()
	form = FeedDataForm(request.form)
	if request.method == 'POST' and form.validate():
		sources_to_update = []
		with db.atomic():
			feed = Feed.create(name=form['name'].data, user=user)
			for source_data in form.sources.entries:
				source, _ = Source.get_or_create(url=source_data['url'].data)
				sources_to_update.append(source.id)
				source_feed = FeedSource.create(
						name=source_data['name'].data,
						feed=feed,
						source=source)
		if sources_to_update:
			add_grab_job(sources_to_update)

		flash('Added new feed')
		return redirect(url_for('feed.manage_feeds'))
	else:
		return render_template('add_feed.html', form=form)

@mod_feed.route('/feed/manage/edit/<int:feed_id>', methods=['GET', 'POST'])
@login_required
def edit_feed(feed_id=0):
	user = current_user._get_current_object()
	feed = (Feed
			.select(Feed, FeedSource, Source)
			.join(FeedSource)
			.join(Source)
			.where(Feed.user == user, Feed.id == feed_id))

	if len(feed) == 0:
		flash('Feed with this index does not exist')
		return redirect('feed.manage_feeds')
	else:
		feed = feed.get()

	form = FeedDataForm(request.form)

	if request.method == 'POST':
		if form.validate():
			sources_to_update = []
			with db.atomic():
				feed.name = form['name'].data
				feed.save()
				(FeedSource
						.delete()
						.where(FeedSource.feed == feed)).execute()
				for source_data in form.sources.entries:
					source, _ = Source.get_or_create(url=source_data['url'].data)
					sources_to_update.append(source.id)
					source_feed = FeedSource.create(
							name=source_data['name'].data,
							feed=feed,
							source=source)
			if sources_to_update:
				add_grab_job(sources_to_update)
			flash('Changes saved')
	else:
		form = FeedDataForm()
		form.name.data = feed.name
		for feed_source in feed.feed_sources:
			source_form = SourceDataForm()
			source_form.name = feed_source.name
			source_form.url = feed_source.source.url
			form.sources.append_entry(source_form)

	return render_template('edit_feed.html', form=form, feed_id=feed_id)

@mod_feed.route('/feed/manage/delete/', methods=['GET', 'POST'])
@login_required
def delete_feed():
	user = current_user._get_current_object()
	if request.method == 'POST':
		form = DeleteFeedForm(request.form)
		if form.validate():
			feed = Feed.get(id=form.feed_id.data)
			#FeedSource.delete().where(FeedSource.feed == feed)
			feed.delete_instance(recursive=True)
			flash('Succsessfully deleted feed')
		else:
			flash('Error occured while deleting feed')

	return redirect(url_for('feed.manage_feeds'))


def get_image_urls(feed_id, page=0):

	urls_key = "feed:{0}:urls".format(feed_id)

	r = redis.StrictRedis(host='localhost', port=6379)

	urls = r.zrange(urls_key, -20 - 20 * page, -1 - 20 * page)
	urls.reverse()


	return [url.decode('utf-8') for url in urls]

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
<title>PT Reader - {% block title %}Base template title{% endblock %}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main/css/style.css') }}" />
</head>
<body>
<script src="{{ url_for('static', filename='jquery/js/jquery-3.1.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='main/js/script.js') }}"></script>

<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid top-container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand">PT-reader</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-left">
				<li><a href="{{ url_for('feed.view_feed') }}">View</a></li>
				<li><a href="{{ url_for('feed.manage_feeds') }}">Manage</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><span class="user-name">{{ [current_user.first_name, current_user.last_name]|join(' ') }}</span></li>
				<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="container-fluid">
	<div class="row">
		<div class="sidebar col-sm-3 col-md-2 ">
			{% block sidebar %}{% endblock %}
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			{% with messages = get_flashed_messages() %}
			{% if messages %}
			<ul>
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% endwith %}
			{% block body %}{% endblock %}
		</div>
	</div>
</div>

</body>
</html>